services:
  mongodb:
    image: mongo:7
    container_name: soil_analytics_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  fastapi-ml:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    ports:
      - "8000:8000"

  express-server:
    build:
      context: ./server
    ports:
      - "5050:5050"
    environment:
      NODE_ENV: development
      PORT: 5050
      FASTAPI_URL: http://fastapi-ml:8000/predict
      MONGODB_URI: mongodb://mongodb:27017/soil_analytics_db
      JWT_SECRET: replace_with_a_real_secret
    depends_on:
      - mongodb
      - fastapi-ml

  react-client:
    build:
      context: ./client
    ports:
      - "80:80"
    depends_on:
      - express-server

volumes:
  mongo_data: